# Generated by Django 4.2.8 on 2023-12-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Name')),
                ('category', models.CharField(max_length=100, verbose_name='Category')),
                ('rate', models.CharField(max_length=10, verbose_name='Rating')),
                ('image', models.ImageField(upload_to='', verbose_name='Poster')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
            },
        ),
    ]
