# Generated by Django 4.2.8 on 2023-12-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_movies_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
